name: midap
channels:
  - defaults
dependencies:
  - python=3.9
  - tensorflow
  - pytorch
  - pip
  - pyqt
  - pip:
    - matplotlib>=3.3.0,<=3.6.3
    - napari
    - PySimpleGUI>=4.60.4
    - scikit-image==0.19.3
    - scikit-image>=0.19.3
    - gitpython
    - omnipose
    - btrack==0.4.6
    - pytest
    - coverage
    - -e .
