name: midap
channels:
  - defaults
dependencies:
  - python=3.10
  - nomkl
  - tensorflow==2.11.1
  - numba
  - pip
  - pyqt
  - pip:
    - matplotlib>=3.3.0,<=3.6.3
    - napari
    - PySimpleGUI>=4.60.4
    - scikit-image==0.19.3
    - gitpython
    - omnipose
    - stardist
    - btrack==0.4.6
    - pytest
    - coverage
    - -e .
