name: Deploy to Public Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Push to public repository
        run: |
          git remote add public-repo https://github.com/Microbial-Systems-Ecology/midap_public
          git push public-repo main:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
